resolver: lts-3.13
packages:
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./warp-tls/client-cert-test
- ./wai-app-static
- ./wai-handler-fastcgi
- ./wai-handler-launch
- ./wai-websockets
- ./wai-conduit
- ./mime-types
- ./auto-update
extra-deps:
- http2-1.3.0
